sudo: required
addons:
  chrome: stable

language: node_js

node_js:
  - "11.10.0"

cache: node_ modules

branches:
  only:
    - travis-ci-demo

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod
deploy:
  provider: heroku
  api_key: b2f08c73-bf24-4812-aa5e-4556d14755f2
  app: rachit-angular7-sample-app
  on:
    repo: cyborg92/angular-7-sample-app