sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "11.10.0"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod
  - ng test